exports.getSquads = function(cb){
	return cb(null,[
	{
		"team":"South Africa",
		"players":[
			{"number":1, "position":"GK", "lastname":"Sandilands", "firstname":"Wayne", "club":"Mamelodi Sundowns"},
			{"number":2, "position":"DF", "lastname":"Gaxa", "firstname":"Siboniso", "club":"Kaizer Chiefs"},
			{"number":3, "position":"DF", "lastname":"Masilela", "firstname":"Tsepo", "club":"Kaizer Chiefs"},
			{"number":4, "position":"DF", "lastname":"Nthethe", "firstname":"Thabo", "club":"Bloemfontein Celtic"},
			{"number":5, "position":"DF", "lastname":"Ngcongca", "firstname":"Anele", "club":"Racing Genk"},
			{"number":6, "position":"MF", "lastname":"Chabangu", "firstname":"Lerato", "club":"Moroka Swallows"},
			{"number":7, "position":"FW", "lastname":"Majoro", "firstname":"Lehlohonolo", "club":"Kaizer Chiefs"},
			{"number":8, "position":"MF", "lastname":"Tshabalala", "firstname":"Siphiwe", "club":"Kaizer Chiefs"},
			{"number":9, "position":"FW", "lastname":"Mphela", "firstname":"Katlego", "club":"Mamelodi Sundowns"},
			{"number":10, "position":"MF", "lastname":"Serero", "firstname":"Thulani", "club":"Ajax"},
			{"number":11, "position":"DF", "lastname":"Matlaba", "firstname":"Thabo", "club":"Orlando Pirates"},
			{"number":12, "position":"MF", "lastname":"Letsholonyane", "firstname":"Reneilwe", "club":"Kaizer Chiefs"},
			{"number":13, "position":"MF", "lastname":"Dikgacoi", "firstname":"Kagisho", "club":"Crystal Palace"},
			{"number":14, "position":"DF", "lastname":"Khumalo", "firstname":"Bongani", "club":"PAOK"},
			{"number":15, "position":"MF", "lastname":"Furman", "firstname":"Dean", "club":"Oldham Athletic"},
			{"number":16, "position":"GK", "lastname":"Khune", "firstname":"Itumeleng", "club":"Kaizer Chiefs"},
			{"number":17, "position":"FW", "lastname":"Parker", "firstname":"Bernard", "club":"Kaizer Chiefs"},
			{"number":18, "position":"MF", "lastname":"Phala", "firstname":"Thuso", "club":"Platinum Stars"},
			{"number":19, "position":"MF", "lastname":"Mahlangu", "firstname":"May", "club":"Helsingborgs IF"},
			{"number":20, "position":"MF", "lastname":"Manyisa", "firstname":"Oupa", "club":"Orlando Pirates"},
			{"number":21, "position":"DF", "lastname":"Sangweni", "firstname":"Siyabonga", "club":"Orlando Pirates"},
			{"number":22, "position":"GK", "lastname":"Meyiwa", "firstname":"Senzo", "club":"Orlando Pirates"},
			{"number":23, "position":"FW", "lastname":"Rantie", "firstname":"Tokelo", "club":"Malmö FF"}
		]
	},
	{
		"team":"Cape Verde",
		"players":[
			{"number":1, "position":"GK", "lastname":"Vozinha", "firstname":null, "club":"Progresso"},
			{"number":2, "position":"DF", "lastname":"Ramos", "firstname":"Guy", "club":"RKC Waalwijk"},
			{"number":3, "position":"DF", "lastname":"Varela", "firstname":"Fernando", "club":"Vaslui"},
			{"number":4, "position":"DF", "lastname":"Josimar", "firstname":null, "club":"Dordrecht"},
			{"number":5, "position":"MF", "lastname":"Babanco", "firstname":null, "club":"Olhanense"},
			{"number":6, "position":"DF", "lastname":"", "firstname":"Nando", "club":"Châteauroux"},
			{"number":7, "position":"MF", "lastname":"Platini", "firstname":null, "club":"Santa Clara"},
			{"number":8, "position":"MF", "lastname":"Varela", "firstname":"Toni", "club":"Sparta Rotterdam"},
			{"number":9, "position":"FW", "lastname":"Tavares", "firstname":"Júlio", "club":"Dijon"},
			{"number":10, "position":"FW", "lastname":"Nhuck", "firstname":null, "club":"Marítimo"},
			{"number":11, "position":"MF", "lastname":"Silva", "firstname":"David", "club":"Olhanense"},
			{"number":12, "position":"GK", "lastname":"Fock", "firstname":null, "club":"Batuque"},
			{"number":13, "position":"DF", "lastname":"Pecks", "firstname":null, "club":"Gil Vicente"},
			{"number":14, "position":"DF", "lastname":"Gegé", "firstname":null, "club":"Marítimo B"},
			{"number":15, "position":"MF", "lastname":"Soares", "firstname":"Marco", "club":"AC Omonia"},
			{"number":16, "position":"MF", "lastname":"Sténio", "firstname":null, "club":"Feirense"},
			{"number":17, "position":"MF", "lastname":"Ronny", "firstname":null, "club":"Fola Esch"},
			{"number":18, "position":"DF", "lastname":"Nivaldo", "firstname":null, "club":"Académica"},
			{"number":19, "position":"FW", "lastname":"Rambé", "firstname":null, "club":"Belenenses"},
			{"number":20, "position":"FW", "lastname":"Mendes", "firstname":"Ryan", "club":"Lille"},
			{"number":21, "position":"FW", "lastname":"Djaniny", "firstname":null, "club":"Olhanense"},
			{"number":22, "position":"GK", "lastname":"Rilly", "firstname":null, "club":"Mindelense"},
			{"number":23, "position":"DF", "lastname":"Carlitos", "firstname":null, "club":"AEL Limassol"}
		]
	},
	{
		"team":"Angola",
		"players":[
			{"number":null, "position":"GK", "lastname":"Lamá", "firstname":null, "club":"Petro Atlético"},
			{"number":null, "position":"GK", "lastname":"Landú", "firstname":null, "club":"C.R.D. Libolo"},
			{"number":null, "position":"GK", "lastname":"Neblú", "firstname":null, "club":"1º de Agosto"},
			{"number":null, "position":"DF", "lastname":"Airosa", "firstname":"Marco", "club":"AEL Limassol"},
			{"number":null, "position":"DF", "lastname":"Amaro", "firstname":null, "club":"1º de Agosto"},
			{"number":null, "position":"DF", "lastname":"Massunguna", "firstname":"Dani", "club":"1º de Agosto"},
			{"number":null, "position":"DF", "lastname":"Miguel", "firstname":null, "club":"Petro Atlético"},
			{"number":null, "position":"DF", "lastname":"Bile", "firstname":"Mingo", "club":"1º de Agosto"},
			{"number":null, "position":"DF", "lastname":"Zuela", "firstname":null, "club":"APOEL"},
			{"number":null, "position":"DF", "lastname":"Bastos", "firstname":null, "club":"Petro Atlético"},
			{"number":null, "position":"DF", "lastname":"Lunguinha", "firstname":null, "club":"Kabuscorp"},
			{"number":null, "position":"DF", "lastname":"Fabrício", "firstname":null, "club":"InterClube"},
			{"number":null, "position":"MF", "lastname":"Gilberto", "firstname":null, "club":"AEL Limassol"},
			{"number":null, "position":"MF", "lastname":"Djalma", "firstname":null, "club":"Kasımpaşa"},
			{"number":null, "position":"MF", "lastname":"Dédé", "firstname":null, "club":"AEL Limassol"},
			{"number":null, "position":"MF", "lastname":"Manuel", "firstname":null, "club":"ASA"},
			{"number":null, "position":"MF", "lastname":"Geraldo", "firstname":null, "club":"Paraná Clube"},
			{"number":null, "position":"MF", "lastname":"Pirolito", "firstname":null, "club":"InterClube"},
			{"number":null, "position":"MF", "lastname":"Diniz", "firstname":"Manucho", "club":"1º de Agosto"},
			{"number":null, "position":"FW", "lastname":"Gonçalves", "firstname":"Manucho", "club":"Real Valladolid"},
			{"number":null, "position":"FW", "lastname":"Mateus", "firstname":null, "club":"Nacional"},
			{"number":null, "position":"FW", "lastname":"Yano", "firstname":null, "club":"Progresso do Sambizanga"},
			{"number":null, "position":"FW", "lastname":"Guilherme", "firstname":null, "club":"FC Vaduz"}
		]
	},
	{
		"team":"Morocco",
		"players":[
			{"number":null, "position":"GK", "lastname":"Lamyaghri", "firstname":"Nadir", "club":"Wydad Casablanca"},
			{"number":null, "position":"GK", "lastname":"Zniti", "firstname":"Anas", "club":"MAS Fez"},
			{"number":null, "position":"GK", "lastname":"Askri", "firstname":"Khalid", "club":"Raja Casablanca"},
			{"number":null, "position":"DF", "lastname":"Benatia", "firstname":"Mehdi", "club":"Udinese"},
			{"number":null, "position":"DF", "lastname":"Kantari", "firstname":"Ahmed", "club":"Stade Brest"},
			{"number":null, "position":"DF", "lastname":"Bergdich", "firstname":"Zakaria", "club":"RC Lens"},
			{"number":null, "position":"DF", "lastname":"El Adoua", "firstname":"Issam", "club":"Vitória de Guimarães"},
			{"number":null, "position":"DF", "lastname":"El Kaoutari", "firstname":"Abdelhamid", "club":"Montpellier"},
			{"number":null, "position":"DF", "lastname":"Noussir", "firstname":"Abdelatif", "club":"MAS Fez"},
			{"number":null, "position":"DF", "lastname":"Chakir", "firstname":"Abderrahim", "club":"FAR Rabat"},
			{"number":null, "position":"MF", "lastname":"Hermach", "firstname":"Adil", "club":"Al Hilal"},
			{"number":null, "position":"MF", "lastname":"El Ahmadi", "firstname":"Karim", "club":"Aston Villa"},
			{"number":null, "position":"MF", "lastname":"Belhanda", "firstname":"Younès", "club":"Montpellier"},
			{"number":null, "position":"MF", "lastname":"Barrada", "firstname":"Abdelaziz", "club":"Getafe"},
			{"number":null, "position":"MF", "lastname":"Chafni", "firstname":"Kamel", "club":"Brest"},
			{"number":null, "position":"MF", "lastname":"Belghazouani", "firstname":"Chahir", "club":"AC Ajaccio"},
			{"number":null, "position":"MF", "lastname":"Namli", "firstname":"Mehdi", "club":"MAT Tetouan"},
			{"number":null, "position":"MF", "lastname":"Kaddioui", "firstname":"Youssef", "club":"FAR Rabat"},
			{"number":null, "position":"FW", "lastname":"El-Arabi", "firstname":"Youssef", "club":"Granada"},
			{"number":null, "position":"FW", "lastname":"El Hamdaoui", "firstname":"Mounir", "club":"Fiorentina"},
			{"number":null, "position":"FW", "lastname":"Amrabat", "firstname":"Nordin", "club":"Galatasaray"},
			{"number":null, "position":"FW", "lastname":"Assaidi", "firstname":"Oussama", "club":"Liverpool"},
			{"number":null, "position":"FW", "lastname":"Hamdallah", "firstname":"Abderrazak", "club":"Olympique Safi"}
		]
	},
	{
		"team":"Ghana",
		"players":[
			{"number":null, "position":"GK", "lastname":"Kwarasey", "firstname":"Adam", "club":"Strømsgodset"},
			{"number":null, "position":"GK", "lastname":"Dauda", "firstname":"Fatau", "club":"Ashanti Gold"},
			{"number":null, "position":"GK", "lastname":"Adjei", "firstname":"Daniel", "club":"Liberty Professionals"},
			{"number":null, "position":"DF", "lastname":"Paintsil", "firstname":"John", "club":"Hapoel Tel Aviv"},
			{"number":null, "position":"DF", "lastname":"Vorsah", "firstname":"Isaac", "club":"Red Bull Salzburg"},
			{"number":null, "position":"DF", "lastname":"Afful", "firstname":"Harrison", "club":"Espérance"},
			{"number":null, "position":"DF", "lastname":"Mensah", "firstname":"Jonathan", "club":"Evian"},
			{"number":null, "position":"DF", "lastname":"Boye", "firstname":"John", "club":"Rennes"},
			{"number":null, "position":"DF", "lastname":"Akaminko", "firstname":"Jerry", "club":"Eskişehirspor"},
			{"number":null, "position":"DF", "lastname":"Boateng", "firstname":"Richard", "club":"Berekum Chelsea"},
			{"number":null, "position":"DF", "lastname":"Awal", "firstname":"Mohamed", "club":"Maritzburg United"},
			{"number":null, "position":"MF", "lastname":"Annan", "firstname":"Anthony", "club":"Osasuna"},
			{"number":null, "position":"MF", "lastname":"Asamoah", "firstname":"Kwadwo", "club":"Juventus"},
			{"number":null, "position":"MF", "lastname":"Boateng", "firstname":"Derek", "club":"Dnipro"},
			{"number":null, "position":"MF", "lastname":"Agyemang-Badu", "firstname":"Emmanuel", "club":"Udinese"},
			{"number":null, "position":"MF", "lastname":"Atsu", "firstname":"Christian", "club":"Porto"},
			{"number":null, "position":"MF", "lastname":"Asante", "firstname":"Solomon", "club":"Berekum Chelsea"},
			{"number":null, "position":"MF", "lastname":"Adomah", "firstname":"Albert", "club":"Bristol City"},
			{"number":null, "position":"MF", "lastname":"Rabiu", "firstname":"Mohammed", "club":"Evian"},
			{"number":null, "position":"FW", "lastname":"Mubarak", "firstname":"Wakaso", "club":"Espanyol"},
			{"number":null, "position":"FW", "lastname":"Gyan", "firstname":"Asamoah", "club":"Al-Ain"},
			{"number":null, "position":"FW", "lastname":"Clottey", "firstname":"Emmanuel", "club":"Espérance"},
			{"number":null, "position":"FW", "lastname":"Boakye", "firstname":"Richmond", "club":"Sassuolo"}
		]
	},
	{
		"team":"Mali",
		"players":[
			{"number":null, "position":"GK", "lastname":"Diakité", "firstname":"Soumbeïla", "club":"Stade Malien"},
			{"number":null, "position":"GK", "lastname":"Samassa", "firstname":"Mamadou", "club":"Guingamp"},
			{"number":null, "position":"GK", "lastname":"Yirango", "firstname":"Aly", "club":"Djoliba"},
			{"number":null, "position":"DF", "lastname":"Coulibaly", "firstname":"Adama", "club":"Auxerre"},
			{"number":null, "position":"DF", "lastname":"Coulibaly", "firstname":"Idrissa", "club":"Lekhwiya"},
			{"number":null, "position":"DF", "lastname":"Coulibaly", "firstname":"Ousmane", "club":"Brest"},
			{"number":null, "position":"DF", "lastname":"Tamboura", "firstname":"Adama", "club":"Randers"},
			{"number":null, "position":"DF", "lastname":"Diawara", "firstname":"Fousseni", "club":"Ajaccio"},
			{"number":null, "position":"DF", "lastname":"N'Diaye", "firstname":"Mahamadou", "club":"Vitória de Guimarães"},
			{"number":null, "position":"DF", "lastname":"Coulibaly", "firstname":"Salif", "club":"Djoliba"},
			{"number":null, "position":"DF", "lastname":"Wague", "firstname":"Molla", "club":"Caen"},
			{"number":null, "position":"MF", "lastname":"Keita", "firstname":"Seydou", "club":"Dalian Aernin"},
			{"number":null, "position":"MF", "lastname":"Sissoko", "firstname":"Mohamed", "club":"PSG"},
			{"number":null, "position":"MF", "lastname":"Traoré", "firstname":"Mahamane", "club":"Metz"},
			{"number":null, "position":"MF", "lastname":"Sow", "firstname":"Samba", "club":"Lens"},
			{"number":null, "position":"MF", "lastname":"Kalilou Traoré", "firstname":"Mohamed", "club":"Sochaux"},
			{"number":null, "position":"MF", "lastname":"Diakité", "firstname":"Samba", "club":"Queens Park Rangers"},
			{"number":null, "position":"MF", "lastname":"Yatabaré", "firstname":"Sambou", "club":"Bastia"},
			{"number":null, "position":"MF", "lastname":"Diarra", "firstname":"Sigamary", "club":"Ajaccio"},
			{"number":null, "position":"FW", "lastname":"Fantamady Diarra", "firstname":"Cheick", "club":"Rennes"},
			{"number":null, "position":"FW", "lastname":"Maïga", "firstname":"Modibo", "club":"West Ham United"},
			{"number":null, "position":"FW", "lastname":"Diabaté", "firstname":"Cheick", "club":"Bordeaux"},
			{"number":null, "position":"FW", "lastname":"Samassa", "firstname":"Mamadou", "club":"Chievo"}
		]
	},
	{
		"team":"Niger",
		"players":[
			{"number":null, "position":"GK", "lastname":"Daouda", "firstname":"Kassaly", "club":"Chippa United"},
			{"number":null, "position":"GK", "lastname":"Rabo", "firstname":"Saminou", "club":"Sahel"},
			{"number":null, "position":"GK", "lastname":"Almouza", "firstname":"Moussa", "club":"AS GNN"},
			{"number":null, "position":"DF", "lastname":"Chikoto", "firstname":"Mohamed", "club":"AS Marsa"},
			{"number":null, "position":"DF", "lastname":"Dan Kowa", "firstname":"Koffi", "club":"Espérance"},
			{"number":null, "position":"DF", "lastname":"Kader", "firstname":"Amadou", "club":"Olympic Niamey"},
			{"number":null, "position":"DF", "lastname":"Alassane", "firstname":"Ismaël", "club":"Al Sahel"},
			{"number":null, "position":"DF", "lastname":"Soumaïla", "firstname":"Mohamed", "club":"Olympic Niamey"},
			{"number":null, "position":"DF", "lastname":"Bachar", "firstname":"Mohamed", "club":"AS Douane"},
			{"number":null, "position":"DF", "lastname":"Fatoukouma", "firstname":"Kourouma", "club":"CR Al Hoceima"},
			{"number":null, "position":"DF", "lastname":"James", "firstname":"Luky", "club":"AS Douane"},
			{"number":null, "position":"MF", "lastname":"Abdoul Karim", "firstname":"Lassina", "club":"Coton Sport"},
			{"number":null, "position":"MF", "lastname":"Laouali", "firstname":"Idrissa", "club":"ASFAN"},
			{"number":null, "position":"MF", "lastname":"N'Gounou", "firstname":"William", "club":"IF Limhamn Bunkeflo"},
			{"number":null, "position":"MF", "lastname":"Boubacar Garba", "firstname":"Issoufou", "club":"CS Hammam-Lif"},
			{"number":null, "position":"MF", "lastname":"Dela Sacko", "firstname":"Souleymane", "club":"Mangasport"},
			{"number":null, "position":"MF", "lastname":"Talatou", "firstname":"Boubacar", "club":"AS GNN"},
			{"number":null, "position":"MF", "lastname":"Koudize", "firstname":"Issiaka", "club":"AS GNN"},
			{"number":null, "position":"MF", "lastname":"Moutari", "firstname":"Amadou", "club":"Le Mans B"},
			{"number":null, "position":"FW", "lastname":"Kamilou", "firstname":"Daouda", "club":"JS Saoura"},
			{"number":null, "position":"FW", "lastname":"Issoufou", "firstname":"Alhassane", "club":"Widad Fez"},
			{"number":null, "position":"FW", "lastname":"Maâzou ", "firstname":"Moussa", "club":"Étoile du Sahel"},
			{"number":null, "position":"FW", "lastname":"Sidibé", "firstname":"Modibo", "club":"Unattached"}
		]
	},
	{
		"team":"Congo DR",
		"players":[
			{"number":null, "position":"GK", "lastname":"Kidiaba", "firstname":"Muteba", "club":"TP Mazembe"},
			{"number":null, "position":"GK", "lastname":"Mandanda", "firstname":"Parfait", "club":"Charleroi"},
			{"number":null, "position":"GK", "lastname":"Bakala", "firstname":"Landu", "club":"MK Etanchéité"},
			{"number":null, "position":"DF", "lastname":"Issama", "firstname":"Mpeko", "club":"Vita Club"},
			{"number":null, "position":"DF", "lastname":"Kasusula", "firstname":"Kilitcho", "club":"TP Mazembe"},
			{"number":null, "position":"DF", "lastname":"Mongongu", "firstname":"Cédric", "club":"Evian"},
			{"number":null, "position":"DF", "lastname":"Mabiala", "firstname":"Larrys", "club":"Karabükspor"},
			{"number":null, "position":"DF", "lastname":"Mulemo", "firstname":"Landry", "club":"K.V. Kortrijk"},
			{"number":null, "position":"DF", "lastname":"Mbemba Mangulu", "firstname":"Chancel", "club":"Anderlecht"},
			{"number":null, "position":"DF", "lastname":"Zakuani", "firstname":"Gabriel", "club":"Peterborough United"},
			{"number":null, "position":"MF", "lastname":"Matumona", "firstname":"Zola", "club":"Mons"},
			{"number":null, "position":"MF", "lastname":"Makiadi", "firstname":"Cédric", "club":"Freiburg"},
			{"number":null, "position":"MF", "lastname":"Diba Ilunga", "firstname":"Yves", "club":"Al-Raed"},
			{"number":null, "position":"MF", "lastname":"Mulumbu", "firstname":"Youssouf", "club":"West Bromwich Albion"},
			{"number":null, "position":"MF", "lastname":"Kisombe", "firstname":"Makuntima", "club":"DC Motema Pembe"},
			{"number":null, "position":"FW", "lastname":"Mputu", "firstname":"Trésor", "club":"TP Mazembe"},
			{"number":null, "position":"FW", "lastname":"LuaLua", "firstname":"Lomana", "club":"Karabükspor"},
			{"number":null, "position":"FW", "lastname":"Kaluyituka", "firstname":"Dioko", "club":"Al Kharaitiyat"},
			{"number":null, "position":"FW", "lastname":"Mbokani", "firstname":"Dieumerci", "club":"Anderlecht"},
			{"number":null, "position":"FW", "lastname":"Kanda", "firstname":"Déo", "club":"TP Mazembe"},
			{"number":null, "position":"FW", "lastname":"Kabangu", "firstname":"Mulota", "club":"TP Mazembe"},
			{"number":null, "position":"FW", "lastname":"Manzia", "firstname":"Budge", "club":"Shark XI"},
			{"number":null, "position":"FW", "lastname":"Luvumbu", "firstname":"Nzinga", "club":"SC Rojolu Lukaku"}
		]
	},
	{
		"team":"Zambia",
		"players":[
			{"number":null, "position":"GK", "lastname":"Mweene", "firstname":"Kennedy", "club":"Free State Stars"},
			{"number":null, "position":"GK", "lastname":"Titima", "firstname":"Joshua", "club":"Power Dynamos"},
			{"number":null, "position":"GK", "lastname":"Munyao", "firstname":"Danny", "club":"Red Arrows"},
			{"number":null, "position":"DF", "lastname":"Musonda", "firstname":"Joseph", "club":"Golden Arrows"},
			{"number":null, "position":"DF", "lastname":"Sunzu", "firstname":"Stophira", "club":"Mazembe"},
			{"number":null, "position":"DF", "lastname":"Kasonde", "firstname":"Francis", "club":"Mazembe"},
			{"number":null, "position":"DF", "lastname":"Himoonde", "firstname":"Hijani", "club":"Mazembe"},
			{"number":null, "position":"DF", "lastname":"Mbola", "firstname":"Emmanuel", "club":"Porto"},
			{"number":null, "position":"DF", "lastname":"Nkausu", "firstname":"Davies", "club":"SuperSport United"},
			{"number":null, "position":"DF", "lastname":"Sinkala", "firstname":"Nathan", "club":"Mazembe"},
			{"number":null, "position":"MF", "lastname":"Kalaba", "firstname":"Rainford", "club":"Mazembe"},
			{"number":null, "position":"MF", "lastname":"Katongo", "firstname":"Felix", "club":"Petro Atletico"},
			{"number":null, "position":"MF", "lastname":"Chansa", "firstname":"Isaac", "club":"Henan Jianye"},
			{"number":null, "position":"MF", "lastname":"Chivuta", "firstname":"Noah", "club":"Free State Stars"},
			{"number":null, "position":"MF", "lastname":"Njovu", "firstname":"William", "club":"Hapoel Be'er Sheva"},
			{"number":null, "position":"MF", "lastname":"Sakuwaha", "firstname":"Jonas", "club":"Al-Merreikh"},
			{"number":null, "position":"MF", "lastname":"Lungu", "firstname":"Chisamba", "club":"Ural Sverdlovsk Oblast"},
			{"number":null, "position":"MF", "lastname":"Mulenga", "firstname":"Mukuka", "club":"Power Dynamos"},
			{"number":null, "position":"FW", "lastname":"Katongo ", "firstname":"Christopher", "club":"Henan Jianye"},
			{"number":null, "position":"FW", "lastname":"Chamanga", "firstname":"James", "club":"Lioaning Whowin"},
			{"number":null, "position":"FW", "lastname":"Mbesuma", "firstname":"Collins", "club":"Orlando Pirates"},
			{"number":null, "position":"FW", "lastname":"Mayuka", "firstname":"Emmanuel", "club":"Southampton"},
			{"number":null, "position":"FW", "lastname":"Mulenga", "firstname":"Jacob", "club":"Utrecht"}
		]
	},
	{
		"team":"Nigeria",
		"players":[
			{"number":null, "position":"GK", "lastname":"Enyeama", "firstname":"Vincent", "club":"Maccabi Tel Aviv"},
			{"number":null, "position":"GK", "lastname":"Ejide", "firstname":"Austin", "club":"Hapoel Be'er Sheva"},
			{"number":null, "position":"GK", "lastname":"Agbim", "firstname":"Chigozie", "club":"Enugu Rangers"},
			{"number":null, "position":"DF", "lastname":"Yobo", "firstname":"Joseph", "club":"Fenerbahçe"},
			{"number":null, "position":"DF", "lastname":"Elderson Echiéjilé", "firstname":"Uwa", "club":"Braga"},
			{"number":null, "position":"DF", "lastname":"Ambrose", "firstname":"Efe", "club":"Celtic"},
			{"number":null, "position":"DF", "lastname":"Egwuekwe", "firstname":"Azubuike", "club":"Warri Wolves"},
			{"number":null, "position":"DF", "lastname":"Oboabona", "firstname":"Godfrey", "club":"Sunshine Stars"},
			{"number":null, "position":"DF", "lastname":"Oshaniwa", "firstname":"Juwon", "club":"Ashdod"},
			{"number":null, "position":"DF", "lastname":"Omeruo", "firstname":"Kenneth", "club":"ADO Den Haag"},
			{"number":null, "position":"MF", "lastname":"John Obi", "firstname":"Mikel", "club":"Chelsea"},
			{"number":null, "position":"MF", "lastname":"Uzoenyi", "firstname":"Ejike", "club":"Enugu Rangers"},
			{"number":null, "position":"MF", "lastname":"Gabriel", "firstname":"Reuben", "club":"Kano Pillars"},
			{"number":null, "position":"MF", "lastname":"Ogude", "firstname":"Fegor", "club":"Vålerenga"},
			{"number":null, "position":"MF", "lastname":"Mba", "firstname":"Sunday", "club":"Enugu Rangers"},
			{"number":null, "position":"MF", "lastname":"Obiorah", "firstname":"Nwankwo", "club":"Gubbio"},
			{"number":null, "position":"MF", "lastname":"Igiebor", "firstname":"Nosa", "club":"Real Betis"},
			{"number":null, "position":"MF", "lastname":"Onazi", "firstname":"Ogenyi", "club":"Lazio"},
			{"number":null, "position":"FW", "lastname":"Uche", "firstname":"Ikechukwu", "club":"Villarreal"},
			{"number":null, "position":"FW", "lastname":"Musa", "firstname":"Ahmed", "club":"CSKA Moscow"},
			{"number":null, "position":"FW", "lastname":"Emenike", "firstname":"Emmanuel", "club":"Spartak Moscow"},
			{"number":null, "position":"FW", "lastname":"Moses", "firstname":"Victor", "club":"Chelsea"},
			{"number":null, "position":"FW", "lastname":"Ideye", "firstname":"Brown", "club":"FC Dynamo Kyiv"}
		]
	},
	{
		"team":"Burkina Faso",
		"players":[
			{"number":null, "position":"GK", "lastname":"Soulama", "firstname":"Abdoulaye", "club":"Asante Kotoko"},
			{"number":null, "position":"GK", "lastname":"Diakité", "firstname":"Daouda", "club":"Lierse"},
			{"number":null, "position":"GK", "lastname":"Sanou", "firstname":"Germain", "club":"Saint-Étienne"},
			{"number":null, "position":"DF", "lastname":"Panandétiguiri", "firstname":"Saïdou", "club":"Royal Antwerp"},
			{"number":null, "position":"DF", "lastname":"Koulibaly", "firstname":"Paul", "club":"Dinamo Bucuresti"},
			{"number":null, "position":"DF", "lastname":"Koné", "firstname":"Bakary", "club":"Lyon"},
			{"number":null, "position":"DF", "lastname":"Traoré", "firstname":"Henri", "club":"Ashanti Gold"},
			{"number":null, "position":"MF", "lastname":"Koffi", "firstname":"Mohamed", "club":"PetroJet"},
			{"number":null, "position":"MF", "lastname":"Kaboré", "firstname":"Charles", "club":"Marseille"},
			{"number":null, "position":"MF", "lastname":"Pitroipa", "firstname":"Jonathan", "club":"Rennes"},
			{"number":null, "position":"MF", "lastname":"Rouamba", "firstname":"Florent", "club":"Sheriff Tiraspol"},
			{"number":null, "position":"MF", "lastname":"Sanou", "firstname":"Wilfried", "club":"Kyoto Sanga"},
			{"number":null, "position":"MF", "lastname":"Balima", "firstname":"Benjamin", "club":"Sheriff Tiraspol"},
			{"number":null, "position":"MF", "lastname":"Razack Traoré", "firstname":"Abdou", "club":"Unattached"},
			{"number":null, "position":"MF", "lastname":"Koné", "firstname":"Djakaridja", "club":"Évian"},
			{"number":null, "position":"MF", "lastname":"Rabo", "firstname":"Ali", "club":"El-Shorta"},
			{"number":null, "position":"MF", "lastname":"Ouattara", "firstname":"Issouf", "club":"Chernomorets Burgas"},
			{"number":null, "position":"MF", "lastname":"Nakoulma", "firstname":"Prejuce", "club":"Górnik Zabrze"},
			{"number":null, "position":"FW", "lastname":"Traoré", "firstname":"Alain", "club":"FC Lorient"},
			{"number":null, "position":"FW", "lastname":"Dagano", "firstname":"Moumouni", "club":"Al-Sailiya"},
			{"number":null, "position":"FW", "lastname":"Bancé", "firstname":"Aristide", "club":"FC Augsburg"},
			{"number":null, "position":"FW", "lastname":"Pierre Koulibaly", "firstname":"Pan", "club":"Al-Dhaid Club"},
			{"number":null, "position":"FW", "lastname":"Dah", "firstname":"Hugues-Wilfried", "club":"Al-Dhaid Club"}
		]
	},
	{
		"team":"Ethiopia",
		"players":[
			{"number":1, "position":"GK", "lastname":"Bancha", "firstname":"Sisay", "club":"Ethiopian Coffee"},
			{"number":2, "position":"DF", "lastname":"Debebe ", "firstname":"Degu", "club":"Saint George"},
			{"number":3, "position":"MF", "lastname":"Zenabu", "firstname":"Yared", "club":"Saint George"},
			{"number":4, "position":"DF", "lastname":"Butako", "firstname":"Abebaw", "club":"Saint George"},
			{"number":5, "position":"DF", "lastname":"Hailu", "firstname":"Aynalem", "club":"Dedebit"},
			{"number":6, "position":"DF", "lastname":"Girma", "firstname":"Alula", "club":"Saint George"},
			{"number":7, "position":"FW", "lastname":"Said", "firstname":"Saladin", "club":"Wadi Degla"},
			{"number":8, "position":"MF", "lastname":"Megersa", "firstname":"Asrat", "club":"EEPCO"},
			{"number":9, "position":"FW", "lastname":"Kebede", "firstname":"Getaneh", "club":"Dedebit"},
			{"number":10, "position":"DF", "lastname":"Bogale", "firstname":"Berhanu", "club":"Dedebit"},
			{"number":11, "position":"FW", "lastname":"Oukri", "firstname":"Oumed", "club":"Defence"},
			{"number":12, "position":"DF", "lastname":"Elias", "firstname":"Biadigling", "club":"Saint George"},
			{"number":13, "position":"FW", "lastname":"Ibrahim", "firstname":"Fuad", "club":"Minnesota Stars"},
			{"number":14, "position":"MF", "lastname":"Teshome", "firstname":"Menyahel", "club":"Dedebit"},
			{"number":15, "position":"MF", "lastname":"Estifanos", "firstname":"Dawit", "club":"Ethiopian Coffee"},
			{"number":16, "position":"MF", "lastname":"Saleh", "firstname":"Yussuf", "club":"Syrianska"},
			{"number":17, "position":"DF", "lastname":"Tesfaye", "firstname":"Siyoum", "club":"Dedebit"},
			{"number":18, "position":"MF", "lastname":"Bekele", "firstname":"Shimelis", "club":"Saint George"},
			{"number":19, "position":"FW", "lastname":"Girma", "firstname":"Adane", "club":"Saint George"},
			{"number":20, "position":"MF", "lastname":"Assefa", "firstname":"Behailu", "club":"Dedebit"},
			{"number":21, "position":"MF", "lastname":"Hintsa", "firstname":"Addis", "club":"Dedebit"},
			{"number":22, "position":"GK", "lastname":"Tassew", "firstname":"Jemal", "club":"Dedebit"},
			{"number":23, "position":"GK", "lastname":"Tadele", "firstname":"Zerihun", "club":"Defence"}
		]
	},
	{
		"team":"Ivory Coast",
		"players":[
			{"number":1, "position":"GK", "lastname":"Barry", "firstname":"Boubacar", "club":"Lokeren"},
			{"number":2, "position":"FW", "lastname":"Koné", "firstname":"Arouna", "club":"Wigan Athletic"},
			{"number":3, "position":"DF", "lastname":"Boka", "firstname":"Arthur", "club":"VfB Stuttgart"},
			{"number":4, "position":"DF", "lastname":"Touré", "firstname":"Kolo", "club":"Manchester City"},
			{"number":5, "position":"MF", "lastname":"Zokora", "firstname":"Didier", "club":"Trabzonspor"},
			{"number":6, "position":"DF", "lastname":"Traoré", "firstname":"Ismaël", "club":"Brest"},
			{"number":7, "position":"FW", "lastname":"Bony", "firstname":"Wilfried", "club":"Vitesse"},
			{"number":8, "position":"FW", "lastname":"Kalou", "firstname":"Salomon", "club":"Lille"},
			{"number":9, "position":"MF", "lastname":"Tioté", "firstname":"Cheick", "club":"Newcastle United"},
			{"number":10, "position":"FW", "lastname":"Gervinho", "firstname":null, "club":"Arsenal"},
			{"number":11, "position":"FW", "lastname":"Drogba", "firstname":"Didier", "club":"Shanghai Shenhua"},
			{"number":12, "position":"DF", "lastname":"Bamba", "firstname":"Sol", "club":"Trabzonspor"},
			{"number":13, "position":"MF", "lastname":"Romaric", "firstname":null, "club":"Real Zaragoza"},
			{"number":14, "position":"FW", "lastname":"Traoré", "firstname":"Lacina", "club":"Anzhi Makhachkala"},
			{"number":15, "position":"FW", "lastname":"Gradel", "firstname":"Max", "club":"Saint-Étienne"},
			{"number":16, "position":"GK", "lastname":"Yeboah", "firstname":"Daniel", "club":"Dijon"},
			{"number":17, "position":"MF", "lastname":"Tiéné", "firstname":"Siaka", "club":"Paris Saint-Germain"},
			{"number":18, "position":"MF", "lastname":"Razak", "firstname":"Abdul", "club":"Manchester City"},
			{"number":19, "position":"MF", "lastname":"Touré", "firstname":"Yaya", "club":"Manchester City"},
			{"number":20, "position":"DF", "lastname":"Lolo", "firstname":"Igor", "club":"Kuban Krasnodar"},
			{"number":21, "position":"DF", "lastname":"Eboué", "firstname":"Emmanuel", "club":"Galatasaray"},
			{"number":22, "position":"FW", "lastname":"Ya Konan", "firstname":"Didier", "club":"Hannover 96"},
			{"number":23, "position":"GK", "lastname":"Ali Sangaré", "firstname":"Badra", "club":"Séwé Sports de San Pedro"}
		]
	},
	{
		"team":"Tunisia",
		"players":[
			{"number":null, "position":"GK", "lastname":"Mathlouthi ", "firstname":"Aymen", "club":"Étoile du Sahel"},
			{"number":null, "position":"GK", "lastname":"Ben Cherifia", "firstname":"Moez", "club":"Espérance"},
			{"number":null, "position":"GK", "lastname":"Ben Mustapha", "firstname":"Farouk", "club":"Bizerte"},
			{"number":null, "position":"DF", "lastname":"Boussaïdi", "firstname":"Anis", "club":"Simferopol (UKR)"},
			{"number":null, "position":"DF", "lastname":"Abdennour", "firstname":"Aymen", "club":"Toulouse (FRA)"},
			{"number":null, "position":"DF", "lastname":"Ifa", "firstname":"Bilel", "club":"Club Africain"},
			{"number":null, "position":"DF", "lastname":"Chammam", "firstname":"Khalil", "club":"Espérance"},
			{"number":null, "position":"DF", "lastname":"Hichri", "firstname":"Walid", "club":"Espérance"},
			{"number":null, "position":"DF", "lastname":"Gharbi", "firstname":"Fatah", "club":"CS Sfaxien"},
			{"number":null, "position":"DF", "lastname":"Bedoui", "firstname":"Rami", "club":"Étoile du Sahel"},
			{"number":null, "position":"DF", "lastname":"Dhaouadi", "firstname":"Chamseddine", "club":"Étoile du Sahel"},
			{"number":null, "position":"MF", "lastname":"Darragi", "firstname":"Oussama", "club":"FC Sion (SUI)"},
			{"number":null, "position":"MF", "lastname":"Traoui", "firstname":"Mejdi", "club":"Espérance"},
			{"number":null, "position":"MF", "lastname":"Ben Yahia", "firstname":"Wissem", "club":"Mersin (TUR)"},
			{"number":null, "position":"MF", "lastname":"Hammami", "firstname":"Chadi", "club":"Kuwait SC (KUW)"},
			{"number":null, "position":"MF", "lastname":"Msakni", "firstname":"Youssef", "club":"Lekhwiya (QAT)"},
			{"number":null, "position":"MF", "lastname":"Mouelhi", "firstname":"Khaled", "club":"Espérance"},
			{"number":null, "position":"MF", "lastname":"Baratli", "firstname":"Hatten", "club":"Club Africain"},
			{"number":null, "position":"MF", "lastname":"Oueslati", "firstname":"Abdelkader", "club":"Atlético Madrid (ESP)"},
			{"number":null, "position":"MF", "lastname":"Khazri", "firstname":"Wahbi", "club":"Bastia (FRA)"},
			{"number":null, "position":"FW", "lastname":"Jemâa", "firstname":"Issam", "club":"Kuwait SC (KUW)"},
			{"number":null, "position":"FW", "lastname":"Dhaouadi", "firstname":"Zouheir", "club":"Evian (FRA)"},
			{"number":null, "position":"FW", "lastname":"Khelifa", "firstname":"Saber", "club":"Evian (FRA)"},
			{"number":null, "position":"FW", "lastname":"Harbaoui", "firstname":"Hamdi", "club":"Lokeren (BEL)"},
			{"number":null, "position":"FW", "lastname":"Ben Youssef", "firstname":"Fakhreddine", "club":"CS Sfaxien"}
		]
	},
	{
		"team":"Algeria",
		"players":[
			{"number":1, "position":"GK", "lastname":"Doukha", "firstname":"Azzedine", "club":"USM El Harrach"},
			{"number":2, "position":"MF", "lastname":"Mostefa", "firstname":"Mehdi", "club":"Ajaccio (FRA)"},
			{"number":3, "position":"DF", "lastname":"Cadamuro-Bentaïba", "firstname":"Liassine", "club":"Real Sociedad (ESP)"},
			{"number":4, "position":"DF", "lastname":"Belkalem", "firstname":"Essaïd", "club":"JS Kabylie"},
			{"number":5, "position":"DF", "lastname":"Halliche", "firstname":"Rafik", "club":"Académica (POR)"},
			{"number":6, "position":"DF", "lastname":"Mesbah", "firstname":"Djamel", "club":"Milan (ITA)"},
			{"number":7, "position":"MF", "lastname":"Boudebouz", "firstname":"Ryad", "club":"Sochaux (FRA)"},
			{"number":8, "position":"MF", "lastname":"Lacen", "firstname":"Medhi", "club":"Getafe (ESP)"},
			{"number":9, "position":"FW", "lastname":"Slimani", "firstname":"Islam", "club":"CR Belouizdad"},
			{"number":10, "position":"MF", "lastname":"Feghouli", "firstname":"Sofiane", "club":"Valencia (ESP)"},
			{"number":11, "position":"MF", "lastname":"Bouazza", "firstname":"Hameur", "club":"Racing Santander (ESP)"},
			{"number":12, "position":"DF", "lastname":"Medjani", "firstname":"Carl", "club":"Ajaccio (FRA)"},
			{"number":13, "position":"FW", "lastname":"Amine Aoudia", "firstname":"Mohamed", "club":"ES Sétif"},
			{"number":14, "position":"MF", "lastname":"Kadir", "firstname":"Foued", "club":"Marseille (FRA)"},
			{"number":15, "position":"FW", "lastname":"Arbi Hillel Soudani", "firstname":"El", "club":"Vitória Guimarães (POR)"},
			{"number":16, "position":"GK", "lastname":"Si Mohamed", "firstname":"Cédric", "club":"JSM Béjaïa"},
			{"number":17, "position":"MF", "lastname":"Guedioura", "firstname":"Adlène", "club":"Nottingham Forest (ENG)"},
			{"number":18, "position":"MF", "lastname":"Lemmouchia", "firstname":"Khaled", "club":"Club Africain (TUN)"},
			{"number":19, "position":"MF", "lastname":"Bezzaz", "firstname":"Yacine", "club":"CS Constantine"},
			{"number":20, "position":"MF", "lastname":"Tedjar", "firstname":"Saad", "club":"USM Alger"},
			{"number":21, "position":"DF", "lastname":"Ghoulam", "firstname":"Faouzi", "club":"Saint-Étienne (FRA)"},
			{"number":22, "position":"DF", "lastname":"Rial", "firstname":"Ali", "club":"JS Kabylie"},
			{"number":23, "position":"GK", "lastname":"M'Bolhi", "firstname":"Raïs", "club":"Krylia Sovetov (RUS)"}
		]
	},
	{
		"team":"Togo",
		"players":[
			{"number":1, "position":"GK", "lastname":"Atsou", "firstname":"Mawugbé", "club":"Maranatha"},
			{"number":2, "position":"DF", "lastname":"Nibombé", "firstname":"Daré", "club":"Boussu Dour (BEL)"},
			{"number":3, "position":"MF", "lastname":"Wome", "firstname":"Dové", "club":"Free State Stars (RSA)"},
			{"number":4, "position":"FW", "lastname":"Adebayor", "firstname":"Emmanuel", "club":"Tottenham Hotspur (ENG)"},
			{"number":5, "position":"DF", "lastname":"Akakpo", "firstname":"Serge", "club":"Žilina (SVK)"},
			{"number":6, "position":"DF", "lastname":"Mamah", "firstname":"Abdoul-Gafar", "club":"Dacia Chişinău (ROM)"},
			{"number":7, "position":"MF", "lastname":"Salifou", "firstname":"Moustapha", "club":null},
			{"number":8, "position":"MF", "lastname":"Amewou", "firstname":"Komlan", "club":"Nîmes (FRA)"},
			{"number":9, "position":"DF", "lastname":"Bossou", "firstname":"Vincent", "club":"Becamex Binh Duong (VIE)"},
			{"number":10, "position":"MF", "lastname":"Ayité", "firstname":"Floyd", "club":"Stade de Reims (FRA)"},
			{"number":11, "position":"FW", "lastname":"Ayité", "firstname":"Jonathan", "club":"Brest (FRA)"},
			{"number":12, "position":"MF", "lastname":"Mani", "firstname":"Sapol", "club":"CA Batna (ALG)"},
			{"number":13, "position":"DF", "lastname":"Ouro-Akoriko", "firstname":"Sadat", "club":"Free State Stars (RSA)"},
			{"number":14, "position":"MF", "lastname":"Segbefia", "firstname":"Prince", "club":"Auxerre (FRA)"},
			{"number":15, "position":"MF", "lastname":"Romao", "firstname":"Alaixys", "club":"Lorient (FRA)"},
			{"number":16, "position":"GK", "lastname":"Agassa", "firstname":"Kossi", "club":"Reims (FRA)"},
			{"number":17, "position":"FW", "lastname":"Gakpé", "firstname":"Serge", "club":"Nantes (FRA)"},
			{"number":18, "position":"FW", "lastname":"Placca Fessou", "firstname":"Mèmè", "club":"OC Agaza"},
			{"number":19, "position":"MF", "lastname":"Amétépé", "firstname":"Kodjo", "club":"Maranatha"},
			{"number":20, "position":"DF", "lastname":"Donou", "firstname":"Kokou", "club":"Maranatha"},
			{"number":21, "position":"DF", "lastname":"Djene", "firstname":"Dakonam", "club":"Coton Sport (CAM)"},
			{"number":22, "position":"FW", "lastname":"Damessi", "firstname":"Kalen", "club":"Lille (FRA)"},
			{"number":23, "position":"GK", "lastname":"Tchagouni", "firstname":"Baba", "club":"Dijon (FRA)"}
		]
	}
]);
};